[package]
name = "fenix"
version = "0.1.0"
authors = ["zakuro <z@kuro.red>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.9.8"
rlibc = "1.0.0"
volatile = "0.3.0"
